### ISSUE TITLE
EC2-Role のみだと strip! = undefined function

### ISSUE THREAD

**Issue by h-imaoka** [y13i/ec2ctl#4]
```ruby
      else
        provider = AWS::Core::CredentialProviders::SharedCredentialFileProvider.new profile_name: get_profile_name
        #config.update credential_provider: provider

        # aws credential bug fix
        hash = provider.get_credentials
        hash[:access_key_id].strip!
      end
```
コマンドラインで直接credential を指定しなかった場合、コチラの処理に流れてくるけど、.aws/credentialもない状態で、この処理に入ると、 hash = {} なので、 hash[:access_key_id].strip! は String.Classでないからエラーになる。
コード的にはstrip!を打つ前に、hash[;access_key_id]が文字列かを判定すればいいと思いますが、credentialの部分は何が正解かわからん。。。そもそもhash = {} のままでも ec2-roleで動くのは確認できた。

**Comment by y13i** [comment]
もう1年以上前で完全に忘れちゃいましたね…
場当たりで直しますが、そのうちaws-sdk v2で作り直そうと思います。
ありがとうございます。

**Comment by y13i** [comment]
#5
